unset arrow 1
unset arrow 2
unset arrow 3
unset arrow 4 
unset arrow 5
unset arrow 6
unset arrow 7
unset arrow 8
unset arrow 9
unset arrow 10
unset arrow 11
unset arrow 12
unset arrow 13
unset arrow 14
unset arrow 15
unset arrow 16